param(
  [Parameter(Mandatory = $true)]
  [string]$RegistryPath,
  [Parameter(Mandatory = $true)]
  [string]$OutputPath
)

$registry = Get-Content -LiteralPath $RegistryPath -Raw
$fileDate = [regex]::Match($registry, '(?m)^File-Date: (.+)$').Groups[1].Value
if ([string]::IsNullOrWhiteSpace($fileDate)) {
  throw "IANA Language Subtag Registry File-Date was not found."
}

$subtags = foreach ($record in ($registry -split "`r?`n%%`r?`n")) {
  if ($record -match '(?m)^Type: language$') {
    $match = [regex]::Match($record, '(?m)^Subtag: ([A-Za-z]+)$')
    if ($match.Success) {
      $match.Groups[1].Value.ToLowerInvariant()
    }
  }
}
$subtags = @($subtags | Sort-Object -Unique)
if ($subtags.Count -eq 0) {
  throw "No language subtags were generated."
}

$packed = ',' + ($subtags -join ',') + ','
$chunks = for ($offset = 0; $offset -lt $packed.Length; $offset += 100) {
  $packed.Substring($offset, [Math]::Min(100, $packed.Length - $offset))
}

$chunkLines = @(
  for ($index = 0; $index -lt $chunks.Count; $index += 1) {
    $suffix = if ($index -lt $chunks.Count - 1) { ' +' } else { '' }
    if ($index -eq 0) {
      'let iana_registered_primary_language_subtags : String = "' + $chunks[$index] + '"' + $suffix
    } else {
      '  "' + $chunks[$index] + '"' + $suffix
    }
  }
)

$lines = @(
  '// Code generated by tools/generate_language_subtags.ps1; do not edit by hand.',
  "// IANA Language Subtag Registry File-Date: $fileDate; $($subtags.Count) unique Type: language subtags.",
  '// Source: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry',
  '',
  '///|'
) + $chunkLines + @(
  '',
  '///|',
  'fn has_iana_registered_primary_language_subtag(value : String) -> Bool {',
  '  iana_registered_primary_language_subtags.contains(',
  '    "," + value.to_lower() + ",",',
  '  )',
  '}'
)

[System.IO.File]::WriteAllText(
  $OutputPath,
  (($lines -join "`n") + "`n"),
  [System.Text.UTF8Encoding]::new($false)
)
